import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
	main: {
		flex: 1,
		backgroundColor: '#565f6e',
	},
	input: {
		height: 50,
		marginLeft: 12,
		marginRight: 12,
		paddingLeft: 10,
		paddingRight: 10,
		borderRadius: 10,
		color: 'white',
		backgroundColor: '#464e5e',
		flexDirection:'row',
		shadowColor: 'black',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.6,
		shadowRadius: 5,
		elevation: 5,
	},
	bus: {
		flex: 1,
	},
	navbar: {
		color: 'white',
		height: 60,
		backgroundColor: '#464e5e',
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	navbarItem: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	dropdownList:{
		position: 'absolute',
		borderRadius: 8,
		maxHeight: 310,
		marginTop: 117,
		marginLeft: 12,
		width: '94%',
		zIndex: 1,
		shadowColor: 'black',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.5,
		shadowRadius: 5,
		elevation: 5,
	},
	dropdownItem:{
		color: 'white',
		height: 45,
		padding: 11,
	},
	searchbtn:{
		paddingLeft: 10,
		justifyContent: 'center'
	},
	addbtn:{
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#8098c4',
		padding: 10,
		color: 'white',
		width: 70,
		borderRadius: 40,
		shadowColor: 'black',
		shadowOpacity: 0.5,
		shadowRadius: 5,
		elevation: 5,
	},
	busitem: {
		backgroundColor: '#464e5e',
		height: 70,
		margin: 12,
		marginBottom: 6,
		shadowOffset: { width: 0, height: 1.5 },
		shadowOpacity: 0.5,
		shadowRadius: 3,
		elevation: 5,
		flexDirection: 'row',
		alignItems: 'center',
		color: 'white',
		padding: 8,
	},
	busbar:{
		flex: 1,
		height: 45,
		marginRight: 10,
		borderRadius: 5,
	},
	centeredView: {
    flex: 1,
		margin: 50,
		marginTop: 200,
		marginBottom: 200,
		backgroundColor: '#636d80',
		borderRadius: 20,
		borderWidth: 5,
		borderColor: '#5a9641',
		padding: 15,
    alignItems: 'center',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.7,
		shadowRadius: 3,
		elevation: 5,
  },
	modalText: {
		color: 'white',
		fontSize: 25,
		marginBottom: 50,
	},
	modalText2: {
		color: 'white',
		fontSize: 17,
	},
	modalItem: {
		alignItems: 'center',
		justifyContent: 'space-between',
		padding: 5,
		flexDirection: 'row',
		backgroundColor: '#464e5e',
		width: '100%',
		height: 60,
		borderRadius: 15,
	},
	modalbtn:{
		color: 'white',
		padding: 10,
		backgroundColor: 'blue',
		borderRadius: 15,
	}
});

export default styles;
